// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.9.25'  // 或者使用最新版本
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        //todo matrix
        //classpath ("com.tencent.matrix:matrix-gradle-plugin:${lib_thirds_matrix_version}") { changing = true }
    }
}

allprojects {
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}